Fixed the issue that was posed yesterday about the undefined reference to the shared pointer. Moreover, make the constructor for the ChassisModel. Will be implementing the closed loop controller next. FEATURE: the chassis object will need to inherit a position tracking system to be able to deliver the absolute coordinates of the base at all times.